"""0001_initial

Revision ID: dd6e49386529
Revises: 
Create Date: 2025-11-10 17:58:13.173315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6e49386529'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('voluntarios_involucrados', sa.String(), nullable=True),
    sa.Column('gatos_objetivo', sa.Integer(), nullable=True),
    sa.Column('gatos_esterilizados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campanas'))
    )
    op.create_index(op.f('ix_campanas_id'), 'campanas', ['id'], unique=False)
    op.create_table('colonias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('numero_gatos', sa.Integer(), nullable=True),
    sa.Column('responsable_voluntario', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colonias'))
    )
    op.create_index(op.f('ix_colonias_id'), 'colonias', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('accepted_terms', sa.Boolean(), nullable=True),
    sa.Column('accepted_terms_date', sa.DateTime(), nullable=True),
    sa.Column('accepted_demo_terms', sa.Boolean(), nullable=True),
    sa.Column('accepted_demo_terms_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('actividades_voluntarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('voluntario_id', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['voluntario_id'], ['users.id'], name=op.f('fk_actividades_voluntarios_voluntario_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actividades_voluntarios'))
    )
    op.create_index(op.f('ix_actividades_voluntarios_id'), 'actividades_voluntarios', ['id'], unique=False)
    op.create_table('gatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('raza', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('edad_num', sa.Integer(), nullable=True),
    sa.Column('edad_unidad', sa.String(), nullable=True),
    sa.Column('estado_salud', sa.String(), nullable=True),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('colonia_id', sa.Integer(), nullable=True),
    sa.Column('evaluacion_sanitaria', sa.String(), nullable=True),
    sa.Column('adoptabilidad', sa.String(), nullable=True),
    sa.Column('fecha_vacunacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_vacuna', sa.String(), nullable=True),
    sa.Column('fecha_desparasitacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_esterilizacion', sa.DateTime(), nullable=True),
    sa.Column('codigo_identificacion', sa.String(length=15), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], name=op.f('fk_gatos_colonia_id_colonias'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gatos'))
    )
    op.create_index(op.f('ix_gatos_id'), 'gatos', ['id'], unique=False)
    op.create_table('inspecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('colonia_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=False),
    sa.Column('acciones_recomendadas', sa.String(), nullable=True),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('archivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], name=op.f('fk_inspecciones_colonia_id_colonias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspecciones'))
    )
    op.create_index(op.f('ix_inspecciones_id'), 'inspecciones', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_notificaciones_usuario_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificaciones'))
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('partes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], name=op.f('fk_partes_responsable_id_users')),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_partes_usuario_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partes'))
    )
    op.create_index(op.f('ix_partes_id'), 'partes', ['id'], unique=False)
    op.create_table('quejas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('colonia_id', sa.Integer(), nullable=True),
    sa.Column('solucion_responsable', sa.String(), nullable=True),
    sa.Column('archivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], name=op.f('fk_quejas_colonia_id_colonias'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quejas'))
    )
    op.create_index(op.f('ix_quejas_id'), 'quejas', ['id'], unique=False)
    op.create_table('usuarios_colonias',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('colonia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colonia_id'], ['colonias.id'], name=op.f('fk_usuarios_colonias_colonia_id_colonias'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usuarios_colonias_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'colonia_id', name=op.f('pk_usuarios_colonias'))
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('gato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gato_id'], ['gatos.id'], name=op.f('fk_actividades_gato_id_gatos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name=op.f('fk_actividades_usuario_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actividades'))
    )
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_table('campanas_gatos',
    sa.Column('campana_id', sa.Integer(), nullable=False),
    sa.Column('gato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], name=op.f('fk_campanas_gatos_campana_id_campanas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gato_id'], ['gatos.id'], name=op.f('fk_campanas_gatos_gato_id_gatos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campana_id', 'gato_id', name=op.f('pk_campanas_gatos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campanas_gatos')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_table('usuarios_colonias')
    op.drop_index(op.f('ix_quejas_id'), table_name='quejas')
    op.drop_table('quejas')
    op.drop_index(op.f('ix_partes_id'), table_name='partes')
    op.drop_table('partes')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_inspecciones_id'), table_name='inspecciones')
    op.drop_table('inspecciones')
    op.drop_index(op.f('ix_gatos_id'), table_name='gatos')
    op.drop_table('gatos')
    op.drop_index(op.f('ix_actividades_voluntarios_id'), table_name='actividades_voluntarios')
    op.drop_table('actividades_voluntarios')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_colonias_id'), table_name='colonias')
    op.drop_table('colonias')
    op.drop_index(op.f('ix_campanas_id'), table_name='campanas')
    op.drop_table('campanas')
    # ### end Alembic commands ###
